version: 2.1
orbs:
  node: circleci/node@5.0.1

jobs:
  codecov:
    executor:
      name: node/default
      tag: '16'
    steps:
      - checkout
      - run: npm run test
      - run: curl -Os https://uploader.codecov.io/latest/linux/codecov
      - run: chmod +x codecov
      - run: ./codecov

workflows:
  upload-to-codecov:
    jobs:
      - codecov