version: 2.1
jobs:
  build:
    docker:
        - image: cimg/node:17.7.2
          auth:
            username: mydockerhub-user
            password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: ls
      - run: npm install
      - save_cache:
          key: my-cache
          paths:
            - my-file.txt
            - my-project/my-dependencies-directory

  tests:
    docker:
        - image: cimg/node:17.7.2
          auth:
            username: mydockerhub-user
            password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: npm run test
      - store_artifacts:
          path: docs
      - restore_cache:
          keys:
            - my-cache


  coverage:
    docker:
        - image: cimg/node:17.7.2
          auth:
            username: mydockerhub-user
            password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: npm run cov
      - store_test_results:
          path: results
      - restore_cache:
          keys:
            - my-cache

          
workflows:
  version: 2
  build_and_artifacts:
    jobs:
      - build
      - tests:
          requires:
            - build
      - coverage:
          requires:
            - tests