version: 2.1
orbs:
  node: circleci/node@5.0.1

jobs:
  codecov:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: sudo npm install -g npm@latest
      - run: npm run test
      - run: curl -Os https://uploader.codecov.io/latest/linux/codecov
      - run: chmod +x codecov
      - run: ./codecov

workflows:
  upload-to-codecov:
    jobs:
      - codecov