version: 2.1
orbs:
  node: circleci/node@5.0.1
jobs:
  build:
    executor:
      name: node/default
      tag: '17'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test
      - run: npm run cov
      - run: echo "my artifact" > artifact.txt
      - store_test_results:
          path: docs
      - store_artifacts:
          path: artifact.txt
