version: 2.1
jobs:
  build:
    docker:
        - image: cimg/node:17.7.2
    steps:
      - checkout
      - run: ls
      - run: npm install
      - run: npm run test
      - run: npm run cov
      - run: echo "my artifact" > artifact.txt
      - store_test_results:
          path: docs
      - store_artifacts:
          path: artifact.txt
          
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
