version: 2.1
jobs:
  build:
    docker:
        - image: cimg/node:17.7.2
          auth:
            username: mydockerhub-user
            password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: ls
      - run: npm install
      - persist_to_workspace:
          root: .
          paths: 
            - .

  tests:
    docker:
        - image: cimg/node:17.7.2
          auth:
            username: mydockerhub-user
            password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: npm run test
      - store_artifacts:
          path: docs
      - persist_to_workspace:
          root: .
          paths: 
            - .

  coverage:
    docker:
        - image: cimg/node:17.7.2
          auth:
            username: mydockerhub-user
            password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: npm run cov
      - store_test_results:
          path: results
      - persist_to_workspace:
          root: .
          paths: 
            - .
          
workflows:
  version: 2
  build_and_artifacts:
    jobs:
      - build
      - tests:
          requires:
            - build
      - coverage:
          requires:
            - tests